name: "npm audit fix"
description: "Run `npm audit fix` and create a pull request"
inputs:
  github_token:
    description: "GitHub token"
    required: false
  branch:
    description: "New Branch"
    required: false
    default: "npm-audit-fix"
  default_branch:
    description: "Default branch"
    required: false
    default: "master"
  commit_title:
    description: "Commit title"
    required: false
    default: "build(deps): npm audit fix"
runs:
  using: "node12"
  main: "dist/index.js"
