name: "npm audit fix"
description: "Run `npm audit fix` and create a pull request"
author: "Masafumi Koba"
inputs:
  github_token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  branch:
    description: "Created branch"
    required: false
    default: "npm-audit-fix-action/fix"
  default_branch:
    description: "Default branch"
    required: false
  commit_title:
    description: "Commit title"
    required: false
    default: "build(deps): npm audit fix"
  labels:
    description: ""
    required: false
    default: "dependencies, javascript, security"
runs:
  using: "node12"
  main: "dist/index.cjs"
