name: "npm audit fix"
description: "Run `npm audit fix` and create a pull request"
author: "Masafumi Koba"
inputs:
  github_token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  github_user:
    description: "GitHub user name for commit changes"
    required: false
    default: ${{ github.actor }}
  github_email:
    description: "GitHub user email for commit changes"
    required: false
    default: "${{ github.actor }}@users.noreply.github.com"
  branch:
    description: "Created branch"
    required: false
    default: "npm-audit-fix-action/fix"
  default_branch:
    description: "Default branch"
    required: false
  commit_title:
    description: "Commit and PR title"
    required: false
    default: "build(deps): npm audit fix"
  labels:
    description: "PR labels"
    required: false
    default: "dependencies, javascript, security"
  npm_args:
    description: "Arguments for the `npm` command"
    required: false
runs:
  using: "node20"
  main: "dist/index.cjs"
