name: "npm audit fix"
description: "Run `npm audit fix` and create a pull request"
author: "Masafumi Koba"
inputs:
  github_token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  github_user:
    description: "GitHub user name for commit changes"
    default: ${{ github.actor }}
    required: false
  github_email:
    description: "GitHub user email for commit changes"
    default: "${{ github.actor }}@users.noreply.github.com"
    required: false
  branch:
    description: "Created branch"
    required: false
    default: "npm-audit-fix-action/fix"
  default_branch:
    description: "Default branch"
    required: false
  commit_title:
    description: "Commit title"
    required: false
    default: "build(deps): npm audit fix"
  labels:
    description: ""
    required: false
    default: "dependencies, javascript, security"
  package_manager:
    description: "Select the package manager used in your project. (npm|yarn)"
    required: false
    default: "npm"
runs:
  using: "node16"
  main: "dist/index.cjs"
