name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: ybiquitous/.github/.github/workflows/dependabot-auto-merge-reusable.yml@3a3a3f01f06fd4c0f834f5df53dc3b38c493d007 # v3.3.1
    permissions:
      contents: write
