name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: ybiquitous/.github/.github/workflows/dependabot-auto-merge-reusable.yml@2f13cf9e69be40562c26464439a9dd258a99cc98 # v3.1.1
    permissions:
      contents: write
