name: npm audit fix

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  npm-audit-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ybiquitous/npm-audit-fix-action@main
        id: npm-audit-fix
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
