name: Release

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  release:
    uses: ybiquitous/.github/.github/workflows/nodejs-release-reusable.yml@3a3a3f01f06fd4c0f834f5df53dc3b38c493d007 # v3.3.1
    with:
      publish: false
      draft: false
      update-semver-tag: true
    permissions:
      contents: write
      id-token: write
