name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  # Run the workflow regularly, as auto-merged PRs by bots may not trigger it.
  schedule:
    - cron: "0 0 1,15 * *"
  # Allow manual triggering of the workflow.
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    env:
      FORCE_COLOR: 1
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install npm
        run: |
          npm install --global npm@"$(npm pkg get 'engines.npm' | jq -r .)"
          npm -v
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build
        env:
          pr_head_ref: ${{ github.event.pull_request.head.ref }}
        run: |
          npm run build
          if git diff --exit-code dist/ ; then
            echo "No changes."
            exit 0
          fi
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add --force -- dist/
          git commit --message "build: update built files"
          git push origin "HEAD:${pr_head_ref}"

  smoke:
    runs-on: ubuntu-latest # ubuntu-slim would require setup-node.
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Run local action for monorepo
        id: npm-audit-fix
        uses: ./
        with:
          branch: "npm-audit-fix-action/test-monorepo"
          commit_title: "test(deps): npm audit fix for monorepo"
          path: |
            .
            examples/monorepo
            examples/monorepo/packages/*
      - name: Verify outputs
        if: ${{ steps.npm-audit-fix.outputs.pull_request_url }}
        shell: bash
        env:
          pull_request_url: ${{ steps.npm-audit-fix.outputs.pull_request_url }}
          branch_name: ${{ steps.npm-audit-fix.outputs.branch_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "pull_request_url: ${pull_request_url}"
          echo "branch_name: ${branch_name}"

          head_ref_name=$(gh pr view "${pull_request_url}" --json headRefName --jq .headRefName)
          echo "head_ref_name: ${head_ref_name}"

          if [[ "${branch_name}" != "${head_ref_name}" ]]; then
            echo "::error::Branch names are unexpected: '${branch_name}' != '${head_ref_name}'"
            exit 1
          fi
      - name: Run local action for subprojects
        id: npm-audit-fix-2
        uses: ./
        with:
          branch: "npm-audit-fix-action/test-subprojects"
          commit_title: "test(deps): npm audit fix for subprojects"
          path: "examples/subprojects/project-a, examples/subprojects/project-b"
      - name: Close test PRs
        env:
          pr_url: ${{ steps.npm-audit-fix.outputs.pull_request_url }}
          pr_url_2: ${{ steps.npm-audit-fix-2.outputs.pull_request_url }}
          GH_TOKEN: ${{ github.token }}
        run: |
          sleep 3
          if [[ -z "${pr_url}" ]]; then
            gh pr close --delete-branch "${pr_url}"
          fi
          if [[ -z "${pr_url_2}" ]]; then
            gh pr close --delete-branch "${pr_url_2}"
          fi

  lint:
    uses: ybiquitous/.github/.github/workflows/nodejs-lint-reusable.yml@11134ce0efbe36bdd758ab41e38fd8e05bf0a10d # v3.3.0
    permissions:
      contents: read
